version: '3.7'

services:
  designpattern:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../design_pattern:/root/design_pattern
    init: true
    tty: true

networks:
  default:
    name: design_pattern_network
